apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: core-interceptors
  app.kubernetes.io/component: interceptors
resources:
  - ../configurations
  - clusterrole.yaml
  - deployment.yaml
  - interceptors.yaml
  - role.yaml
  - secret.yaml
  - serviceaccount.yaml
images:
  - name: gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/interceptors
    newTag: v0.25.3@sha256:777e1489bc37e8f06956319331e353a21d53f8d645dec7b1eb986a42fd94316b
