apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: core-interceptors
  app.kubernetes.io/component: interceptors
resources:
  - ../configurations
  - clusterrole.yaml
  - deployment.yaml
  - interceptors.yaml
  - role.yaml
  - secret.yaml
  - serviceaccount.yaml
images:
  - name: gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/interceptors
    newTag: v0.26.2@sha256:80508a5a9c014cda7ab34bed2c32cbabfcadab58f24dc098d469a1f4d1ee531e
