apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
    app.kubernetes.io/part-of: tekton-triggers
resources:
  - crd-clusterinterceptor.yaml
  - crd-clustertriggerbinding.yaml
  - crd-eventlistener.yaml
  - crd-interceptor.yaml
  - crd-trigger.yaml
  - crd-triggerbinding.yaml
  - crd-triggertemplate.yaml
  - ./controller
  - ./core-interceptors
  - ./webhook
  - clusterrole.yaml
  - clusterrole-aggregate-edit.yaml
  - clusterrole-aggregate-view.yaml
  - config-defaults-triggers.yaml
  - config-feature-flags.yaml
  - config-info.yaml
  - config-logging.yaml
  - config-observability.yaml
  - role-tekton-triggers-info.yaml
