apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: events
resources:
  - clusterrole.yaml
  - events.yaml
  - role.yaml
  - serviceaccount.yaml
images:
  - name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/events
    newTag: v0.50.1@sha256:02dc586383a945fbd9cd2b8d58d597866dc36411bec50ead19527004e451b004
