apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: events
resources:
  - ../../configurations/prometheus-operator
  - clusterrole.yaml
  - config-leader-election.yaml
  - events.yaml
  - podmonitor.yaml
  - role.yaml
  - serviceaccount.yaml
images:
  - name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/events
    newTag: v0.54.0@sha256:3b3df2e9f5860c3c29f68012b5aa2a9870e47dd83b5287dd4e7666219fa5134f
