apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: events
resources:
  - ../../configurations/prometheus-operator
  - clusterrole.yaml
  - config-leader-election.yaml
  - events.yaml
  - podmonitor.yaml
  - role.yaml
  - serviceaccount.yaml
images:
  - name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/events
    newTag: v0.60.2@sha256:edce1ec808b27d9eb560a77ccc771a0c2a6335e9aaf0cafa618eea880caf374d
