apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: webhook
resources:
  - ../../configurations/prometheus-operator
  - clusterrole.yaml
  - config-leader-election.yaml
  - hpa.yaml
  - role.yaml
  - serviceaccount.yaml
  - servicemonitor.yaml
  - webhook.yaml
  - webhooks.yaml
images:
  - name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook
    newTag: v0.61.1@sha256:b9e5dc555d41fbb8e9752bb9ba51ce3b7205081f174b7706a4dd193596d5eb35
