apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: webhook
resources:
  - ../../configurations/prometheus-operator
  - clusterrole.yaml
  - config-leader-election.yaml
  - hpa.yaml
  - role.yaml
  - serviceaccount.yaml
  - servicemonitor.yaml
  - webhook.yaml
  - webhooks.yaml
images:
  - name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook
    newTag: v0.56.0@sha256:99824836bb47c1d9e21efdeff56e02b9426fe2323a22625b7af4f66a4028a5b4
