apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: webhook
resources:
  - clusterrole.yaml
  - hpa.yaml
  - role.yaml
  - serviceaccount.yaml
  - webhook.yaml
  - webhooks.yaml
images:
  - name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook
    newTag: v0.53.0@sha256:da5cefe4b29a2c0904ccdae95d5bf668068c2ac1fc1618c239425fc616360568
