apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: controller
resources:
  - ../../configurations/prometheus-operator
  - clusterrole.yaml
  - config-leader-election.yaml
  - controller.yaml
  - podmonitor.yaml
  - role.yaml
  - serviceaccount.yaml
patches:
  - # Let's keep all the images here in the kustomization file
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: tekton-pipelines-controller
      spec:
        template:
          spec:
            containers:
              - name: tekton-pipelines-controller
                env:
                  - name: ENTRYPOINT_IMAGE
                    # renovate: datasource=docker
                    value: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.61.0@sha256:56da5618bf121a8c7d81e5a7260b38ab614f3e439cc3327c93ca2251773ab43b
                  - name: NOP_IMAGE
                    # renovate: datasource=docker
                    value: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/nop:v0.61.0@sha256:a5ce35b36031084455ae2002f7466b7bdaf49c46a9f7f9ec4d2228e262ee146e
                  - name: SIDECARLOGRESULTS_IMAGE
                    # renovate: datasource=docker
                    value: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/sidecarlogresults:v0.61.0@sha256:7f458d2460e45b41586730ceb8f683a8ef4ae9699454af2454509527812574dd
                  - name: WORKINGDIRINIT_IMAGE
                    # renovate: datasource=docker
                    value: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/workingdirinit:v0.61.0@sha256:9fcd6e9ecacb2243e5b56bd4c042c2c585fbabf2d49c20d9c09b178ba8876083
                  - name: SHELL_IMAGE
                    # renovate: datasource=docker
                    value: cgr.dev/chainguard/busybox:latest@sha256:19f02276bf8dbdd62f069b922f10c65262cc34b710eea26ff928129a736be791
                  - name: SHELL_IMAGE_WIN
                    # renovate: datasource=docker
                    value: mcr.microsoft.com/powershell:nanoserver@sha256:b6d5ff841b78bdf2dfed7550000fd4f3437385b8fa686ec0f010be24777654d6
images:
  - name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller
    newTag: v0.61.0@sha256:b4ec78d2267e176abc7aac89f90fe36d8698f5b4472a64b738b69f13e84f6b36
