apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: controller
resources:
  - ../../configurations/prometheus-operator
  - clusterrole.yaml
  - config-leader-election.yaml
  - controller.yaml
  - podmonitor.yaml
  - role.yaml
  - serviceaccount.yaml
patches:
  - # Let's keep all the images here in the kustomization file
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: tekton-pipelines-controller
      spec:
        template:
          spec:
            containers:
              - name: tekton-pipelines-controller
                env:
                  - name: ENTRYPOINT_IMAGE
                    # renovate: datasource=docker
                    value: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.59.0@sha256:d602e0be27f766ae86949b485f9d5045b86f63f5c9ef0a6fe9d8a10283cd4aad
                  - name: NOP_IMAGE
                    # renovate: datasource=docker
                    value: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/nop:v0.59.0@sha256:6eb172889e7f8978d990b9cf7f71daeb8db9a9f7b51b8163cd8a482df8fd47c5
                  - name: SIDECARLOGRESULTS_IMAGE
                    # renovate: datasource=docker
                    value: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/sidecarlogresults:v0.59.0@sha256:52e3a25f57fcb2d59c3a4392118c6a22e0f66dca79423e2054f00919f80f77b2
                  - name: WORKINGDIRINIT_IMAGE
                    # renovate: datasource=docker
                    value: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/workingdirinit:v0.59.0@sha256:5162b2607b98ea965610dda729991f6e573670adabf86195af34a5dea5de1418
                  - name: SHELL_IMAGE
                    # renovate: datasource=docker
                    value: cgr.dev/chainguard/busybox:latest@sha256:19f02276bf8dbdd62f069b922f10c65262cc34b710eea26ff928129a736be791
                  - name: SHELL_IMAGE_WIN
                    # renovate: datasource=docker
                    value: mcr.microsoft.com/powershell:nanoserver@sha256:b6d5ff841b78bdf2dfed7550000fd4f3437385b8fa686ec0f010be24777654d6
images:
  - name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller
    newTag: v0.59.0@sha256:8178d0e51a35be3ebb4c6f1a2ffee2b7657daaad321ebda50b4a4718037d9208
