apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: controller
resources:
  - ../../configurations/prometheus-operator
  - clusterrole.yaml
  - config-leader-election.yaml
  - controller.yaml
  - podmonitor.yaml
  - role.yaml
  - serviceaccount.yaml
patches:
  - # Let's keep all the images here in the kustomization file
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: tekton-pipelines-controller
      spec:
        template:
          spec:
            containers:
              - name: tekton-pipelines-controller
                env:
                  - name: ENTRYPOINT_IMAGE
                    # renovate: datasource=docker
                    value: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.56.1@sha256:8c6f10d9553b7734ba3d07ea1cdd08df80e8147cb8e0167371e386ba5ab98793
                  - name: NOP_IMAGE
                    # renovate: datasource=docker
                    value: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/nop:v0.56.1@sha256:9b2ff1059e7e721065774e3a1cf98dde4eb49435aa9c60bdf8939d71a5e2d0e7
                  - name: SIDECARLOGRESULTS_IMAGE
                    # renovate: datasource=docker
                    value: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/sidecarlogresults:v0.56.1@sha256:4c9116067a23e57091697e309ac9b6f8ecf1504fbda670c699742cfcdbb52116
                  - name: WORKINGDIRINIT_IMAGE
                    # renovate: datasource=docker
                    value: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/workingdirinit:v0.56.1@sha256:630d15584ff3523e539c66425b073cd489cb04a7093e1d48d46966a09b4b1f21
                  - name: SHELL_IMAGE
                    # renovate: datasource=docker
                    value: cgr.dev/chainguard/busybox:latest@sha256:19f02276bf8dbdd62f069b922f10c65262cc34b710eea26ff928129a736be791
                  - name: SHELL_IMAGE_WIN
                    # renovate: datasource=docker
                    value: mcr.microsoft.com/powershell:nanoserver@sha256:b6d5ff841b78bdf2dfed7550000fd4f3437385b8fa686ec0f010be24777654d6
images:
  - name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller
    newTag: v0.56.1@sha256:293ebe7b57773aa19fd3c77e03dac218668ed9d4633a9468c921ec79e2fe11c1
