apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: controller
resources:
  - ../../configurations/prometheus-operator
  - clusterrole.yaml
  - config-leader-election.yaml
  - controller.yaml
  - podmonitor.yaml
  - role.yaml
  - serviceaccount.yaml
patches:
  - # Let's keep all the images here in the kustomization file
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: tekton-pipelines-controller
      spec:
        template:
          spec:
            containers:
              - name: tekton-pipelines-controller
                env:
                  - name: ENTRYPOINT_IMAGE
                    # renovate: datasource=docker
                    value: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.57.0@sha256:223a61b2b9798a679cbf36a8abad6f8fa13bf7bd9f11c8a2fd91d2afd3e14690
                  - name: NOP_IMAGE
                    # renovate: datasource=docker
                    value: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/nop:v0.57.0@sha256:6e65d18c3ffe76da47df74bb854d4b86452f6080b981d249c5e6ca7bdc328240
                  - name: SIDECARLOGRESULTS_IMAGE
                    # renovate: datasource=docker
                    value: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/sidecarlogresults:v0.57.0@sha256:e84e852fe5e777c072899dbadaf265fa784924587349926108340130cb48eb09
                  - name: WORKINGDIRINIT_IMAGE
                    # renovate: datasource=docker
                    value: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/workingdirinit:v0.57.0@sha256:6f97f5c9d4c4effdaa81a8cf2e7f7be39b366a91a0973cb0f10c44a033c6b042
                  - name: SHELL_IMAGE
                    # renovate: datasource=docker
                    value: cgr.dev/chainguard/busybox:latest@sha256:19f02276bf8dbdd62f069b922f10c65262cc34b710eea26ff928129a736be791
                  - name: SHELL_IMAGE_WIN
                    # renovate: datasource=docker
                    value: mcr.microsoft.com/powershell:nanoserver@sha256:b6d5ff841b78bdf2dfed7550000fd4f3437385b8fa686ec0f010be24777654d6
images:
  - name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller
    newTag: v0.57.0@sha256:111353d2fdf32fa8c51195dca4447582333b44419d57d66c915f59b89cde0ec3
