apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: controller
resources:
  - clusterrole.yaml
  - controller.yaml
  - role.yaml
  - serviceaccount.yaml
patches:
  - # Let's keep all the images here in the kustomization file
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: tekton-pipelines-controller
      spec:
        template:
          spec:
            containers:
              - name: tekton-pipelines-controller
                env:
                  - name: ENTRYPOINT_IMAGE
                    value: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.50.1@sha256:0c66040a16142a598d5aa9f310b1cbf66e843aa7114188f5d0ab5d36b463a09b
                  - name: NOP_IMAGE
                    value: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/nop:v0.50.1@sha256:537f2e9884fb14d5b42f1d749c62d7404bf061ec8983a07a15a556a2b560875a
                  - name: SIDECARLOGRESULTS_IMAGE
                    value: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/sidecarlogresults:v0.50.1@sha256:dbcbd3b156ac74539f25780f639891489130fdee72871351e5a8b9ff194cc7bb
                  - name: WORKINGDIRINIT_IMAGE
                    value: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/workingdirinit:v0.50.1@sha256:cdce382e0e5fa8e29132f1cbae8de2610f050ad5db9a355a5a93b913a03b209f
                  - name: SHELL_IMAGE
                    value: cgr.dev/chainguard/busybox@sha256:19f02276bf8dbdd62f069b922f10c65262cc34b710eea26ff928129a736be791
                  - name: SHELL_IMAGE_WIN
                    value: mcr.microsoft.com/powershell:nanoserver@sha256:b6d5ff841b78bdf2dfed7550000fd4f3437385b8fa686ec0f010be24777654d6
images:
  - name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller
    newTag: v0.50.1@sha256:9025991c337374dadce6d49e29fbcf86b233ab8f5f96748c67293b2285c3e0b6
