apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: resolvers
resources:
  - ../../configurations/prometheus-operator
  - bundleresolver-config.yaml
  - cluster-resolver-config.yaml
  - clusterrole.yaml
  - config-feature-flags.yaml
  - config-leader-election.yaml
  - deployment.yaml
  - git-resolver-config.yaml
  - hubresolver-config.yaml
  - http-resolver-config.yaml
  - role.yaml
  - serviceaccount.yaml
  - servicemonitor.yaml
  - service.yaml
images:
  - name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/resolvers
    newTag: v0.61.1@sha256:8c74da3a972aa32c6100fcd2ac4e37aa6677ce2fc29743d757cd79fec5068b20
