apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: resolvers
resources:
  - ../../configurations/prometheus-operator
  - bundleresolver-config.yaml
  - cluster-resolver-config.yaml
  - clusterrole.yaml
  - config-feature-flags.yaml
  - config-leader-election.yaml
  - deployment.yaml
  - git-resolver-config.yaml
  - hubresolver-config.yaml
  - http-resolver-config.yaml
  - role.yaml
  - serviceaccount.yaml
  - servicemonitor.yaml
  - service.yaml
images:
  - name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/resolvers
    newTag: v0.55.0@sha256:7a2494ccb181109e3419c519c15a6010c0cf2cd53710f1515550e3e130d9bae8
