apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: resolvers
resources:
  - ../../configurations/prometheus-operator
  - bundleresolver-config.yaml
  - cluster-resolver-config.yaml
  - clusterrole.yaml
  - config-feature-flags.yaml
  - config-leader-election.yaml
  - deployment.yaml
  - git-resolver-config.yaml
  - hubresolver-config.yaml
  - http-resolver-config.yaml
  - role.yaml
  - serviceaccount.yaml
  - servicemonitor.yaml
  - service.yaml
images:
  - name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/resolvers
    newTag: v0.58.0@sha256:9d2a81157a7a10286d6ea3a3885ad3896f3849884d644a70d6926ca3ef98eb14
