apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: controller
resources:
  - clusterrolebinding.yaml
  - config-leader-election.yaml
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
patches:
  - # Let's keep all the images here in the kustomization file
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: tekton-triggers-controller
      spec:
        template:
          spec:
            containers:
              - name: tekton-triggers-controller
                env:
                  - name: EL_IMAGE
                    # renovate: datasource=docker
                    value: gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/eventlistenersink:v0.29.1@sha256:d12845f2d3aea7a35616e94959e7b3b2e07386ac9121dae9d6eba91606fb03db
images:
  - name: gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/controller
    newTag: v0.29.1@sha256:34aa909bd6de6b24c78004bbd5eac0d8d1f438bba4be5beb385b61b88977bffe
