apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: controller
resources:
  - clusterrolebinding.yaml
  - config-leader-election.yaml
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
patches:
  - # Let's keep all the images here in the kustomization file
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: tekton-triggers-controller
      spec:
        template:
          spec:
            containers:
              - name: tekton-triggers-controller
                env:
                  - name: EL_IMAGE
                    # renovate: datasource=docker
                    value: gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/eventlistenersink:v0.25.2@sha256:801bdcec708b86dea208f67e343016cddc3762b7cd36e0244d35be0e0da889e0
images:
  - name: gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/controller
    newTag: v0.25.2@sha256:ed66711c2bc89d24adfff57772a22ef4f5be1c0d1d05cac4bee73c841fa54d9c
