apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: controller
resources:
  - clusterrolebinding.yaml
  - config-leader-election.yaml
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
patches:
  - # Let's keep all the images here in the kustomization file
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: tekton-triggers-controller
      spec:
        template:
          spec:
            containers:
              - name: tekton-triggers-controller
                env:
                  - name: EL_IMAGE
                    # renovate: datasource=docker
                    value: gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/eventlistenersink:v0.26.0@sha256:f3a448a5834ae092ed548508e83b080f57f90b0fb4c1e7227fe80366053ec764
images:
  - name: gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/controller
    newTag: v0.26.0@sha256:b12fd00f697b861d2edeb39588df3d8038a1ed3c81f16ff0349512cd6da5dac1
