apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: controller
resources:
  - clusterrolebinding.yaml
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
patches:
  - # Let's keep all the images here in the kustomization file
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: tekton-triggers-controller
      spec:
        template:
          spec:
            containers:
              - name: tekton-triggers-controller
                env:
                  - name: EL_IMAGE
                    # renovate: datasource=docker
                    value: gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/eventlistenersink:v0.25.0@sha256:a029b639f5a69913002f944e63bb113d05e289fc1c885257665dd0d116315c9c
images:
  - name: gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/controller
    newTag: v0.25.0@sha256:cf9aa3895eb475e491173576927a8c066c7f537630306233b39985509bec186c
