apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: webhook
resources:
  - clusterrolebinding.yaml
  - config-leader-election.yaml
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
  - role.yaml
  - webhooks.yaml
images:
  - name: gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/webhook
    newTag: v0.26.0@sha256:c64e0da277da7936ed7302aa8669b5624916b8d1feeb565746479904bfc77e83
